#!/bin/bash

# Get the directory where this script is located
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
MAYA_ROOT="$(dirname "$SCRIPT_DIR")"

# Create output directory if it doesn't exist
mkdir -p "$SCRIPT_DIR/spv"

# Compile the compute shader
echo "Compiling 4d_tensor_operations.comp..."
if ! glslc -o "$SCRIPT_DIR/spv/4d_tensor_operations.spv" "$SCRIPT_DIR/4d_tensor_operations.comp"; then
    echo "Error: Failed to compile shader"
    exit 1
fi

# Create the target directory if it doesn't exist
mkdir -p "$MAYA_ROOT/src/vulkan"

# Create a Zig module with the shader bytecode
echo "Generating shader module..."
cat > "$MAYA_ROOT/src/vulkan/shaders.zig" << 'EOL'
// This file is auto-generated by compile_shaders.sh
// Do not edit manually

pub const shader_4d_tensor_operations = @embedFile("../../shaders/spv/4d_tensor_operations.spv");
EOL

echo "Shader compilation complete!"
echo "SPIR-V shader written to: $SCRIPT_DIR/spv/4d_tensor_operations.spv"
echo "Zig module written to: $MAYA_ROOT/src/vulkan/shaders.zig"
