// This file is auto-generated by build.zig
// It exports the shader files as byte arrays that can be embedded in the binary

// 4D tensor operations shaders for different data types
pub const shader_float = @embedFile("4d_tensor_operations_float.comp.spv");
pub const shader_int = @embedFile("4d_tensor_operations_int.comp.spv");
pub const shader_uint = @embedFile("4d_tensor_operations_uint.comp.spv");
