#!/bin/bash

# Create generated directory if it doesn't exist
mkdir -p src/vulkan/compute/generated

# Run the Zig script to generate shader files
zig run scripts/generate_shaders.zig

# Create a shaders.zig file that re-exports all the generated shaders
cat > src/vulkan/compute/shaders.zig << 'EOL'
// This file is auto-generated by generate_shaders.sh
// It re-exports the generated shader byte arrays

pub const float = @import("generated/4d_tensor_operations_float.comp.zig").data;
pub const int = @import("generated/4d_tensor_operations_int.comp.zig").data;
pub const uint = @import("generated/4d_tensor_operations_uint.comp.zig").data;
EOL
