#!/usr/bin/env python3
import os

def main():
    shader_files = [
        ("float", "shaders/4d_tensor_operations_float.comp.spv"),
        ("int", "shaders/4d_tensor_operations_int.comp.spv"),
        ("uint", "shaders/4d_tensor_operations_uint.comp.spv"),
    ]
    
    output = [
        "// This file is auto-generated by scripts/generate_shaders_simple.py",
        "// Do not edit manually",
        "",
        "// 4D tensor operations shaders for different data types",
        "",
    ]
    
    for name, path in shader_files:
        with open(path, 'rb') as f:
            data = f.read()
        
        output.append(f"pub const {name} = [_]u8{{\n    " + 
            ", ".join(f"0x{b:02x}" for b in data[:16]) + 
            ",\n    " + 
            ", ".join(f"0x{b:02x}" for b in data[16:]) + 
            "\n};\n")
    
    os.makedirs("src/vulkan/compute", exist_ok=True)
    with open("src/vulkan/compute/shaders.zig", 'w') as f:
        f.write("\n".join(output))

if __name__ == "__main__":
    main()
