//! Build-time configuration options for the MAYA project
//! This file is generated by the build system

const std = @import("std");

// Import build options from the build system
const build_options = @import("build_options");

// Build configuration options
pub const options = struct {
    /// Whether GPU support is enabled
    pub const enable_gpu = build_options.enable_gpu;
};
